name: Github Action soulmouctar
on:
  - push
jobs:
  Mkdocs-project:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3

      - name: "List repository files"
        run: "ls -al"
      - name: "Install python"
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: "Installing mkdocs"
        run: pip install mkdocs
      - name: "Deploy project"
        run: mkdocs gh-deploy --force
      - name: "finish"
        run: echo "🎉 The job was successful."
      - name: "show all env"
        run: printenv